### ISSUE TITLE
NoMethodError: undefined method `compile' for #<String:0xc6ba147>

### ISSUE THREAD

**Issue by donv** [jruby/activerecord-jdbc-adapter#660] opened 2015-07-02 12:21 UTC
As seen in travis:

https://travis-ci.org/jruby/activerecord-jdbc-adapter/jobs/68947526#L1519

Anybody looked at this yet?

**Comment by kares** [comment] 2015-07-17 06:54
should be a duplicate of https://github.com/jruby/activerecord-jdbc-adapter/issues/662 ... please confirm

**Comment by donv** [comment] 2015-07-17 10:26
Yes, should go away when you merge the recent changes form 1-3-stable.

**Closed** 2015-07-25 12:55 UTC
Labels: derby, rails-4.2
