### ISSUE TITLE
Postgres using triggers does not return id, raises exception

### ISSUE THREAD

**Issue by bauerjon** [jruby/activerecord-jdbc-adapter#709] opened 2016-01-22 22:20 UTC
Using postgres triggers you cannot get the id back from the database upon insertion. I found this out while using pg_partman. https://github.com/keithf4/pg_partman/issues/18

This causes an exception in 'last_inserted_id'
https://github.com/jruby/activerecord-jdbc-adapter/blob/v1.3.19/lib/arjdbc/postgresql/adapter.rb#L687

```
   # result  is #<ActiveRecord::Result:0x68651690>
   result.first.first[1] # .first = nil .first => Exception!
```

```
NoMethodError: undefined method `first' for nil:NilClass
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-jdbc-adapter-1.3.17/lib/arjdbc/postgresql/adapter.rb:688:in `last_inserted_id'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/connection_adapters/abstract/database_statements.rb:99:in `insert'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/connection_adapters/abstract/query_cache.rb:19:in `insert'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/relation.rb:64:in `insert'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/persistence.rb:504:in `_create_record'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/attribute_methods/dirty.rb:87:in `_create_record'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/callbacks.rb:306:in `_create_record'
        from org/jruby/RubyProc.java:271:in `call'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:113:in `call'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:552:in `compile'
        from org/jruby/RubyProc.java:271:in `call'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:502:in `call'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activesupport-4.1.13/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/callbacks.rb:306:in `_create_record'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/timestamp.rb:57:in `_create_record'
        from /var/groupon/jboss/backbeat/apps/backbeat/shared/bundle/jruby/1.9/gems/activerecord-4.1.13/lib/active_record/persistence.rb:484:in `create_or_update'
... 35 levels...
```

AR-JDBC Version 
1.3.17 (seems to be same code as on master)

ActiveRecord Version
4.1.13

JRuby Version
jruby 1.7.11 (1.9.3p392)
## 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30129016-postgres-using-triggers-does-not-return-id-raises-exception?utm_campaign=plugin&utm_content=tracker%2F136963&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F136963&utm_medium=issues&utm_source=github).

**Comment by bauerjon** [comment] 2016-02-03 23:52
@kares is it preferable if I just do a pull request?

**Comment by kares** [comment] 2016-02-04 06:14
@bauerjon yes please ... preferably with a test-case. 1-3-stable branch if you want to see this in next 1.3

**Comment by kares** [comment] 2017-05-08 11:19
closing as duplicate of #773 (same cause and already fixed on 1-3-stable)

**Closed by kares** 2017-05-08 11:19 UTC
Labels: postgres, rails-4.x
