### ISSUE TITLE
 Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by ebbflowgo** [jruby/activerecord-jdbc-adapter#638] opened 2015-04-10 02:03 UTC
Simply looking to require the gem in a ruby file and run it. Returning an error of:
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern

Running code as jruby -S database.rb

Gem file, error and base_ext.rb are shown here:
[Gist of Error](https://gist.github.com/ebbflowgo/c706b2ab9cc8abb95ee2)

**Comment by kares** [comment] 2015-04-10 05:54
you're somehow double loading something : 
```
/Users/hank/.rvm/gems/jruby-1.7.19/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:587 warning: already initialized constant Reference
/Users/hank/.rvm/gems/jruby-1.7.19/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:37 warning: already initialized constant MAPPING
/Users/hank/.rvm/gems/jruby-1.7.19/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:189 warning: already initialized constant UTC_OFFSET_WITH_COLON
/Users/hank/.rvm/gems/jruby-1.7.19/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:190 warning: already initialized constant UTC_OFFSET_WITHOUT_COLON
/Users/hank/.rvm/gems/jruby-1.7.19/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:40 warning: already initialized constant BLACKLISTED_ARRAY_METHODS
```

that is likely the cause of the failure ... you should figure out why is that happening (e.g. debug the require/load-service) and than see if it's actually a JRuby bug or something that you're doing wrong.

**Comment by ebbflowgo** [comment] 2015-04-10 12:34
seems to be the same as: https://github.com/jruby/jruby/issues/2286

**Comment by ebbflowgo** [comment] 2015-04-10 12:39
Looks like it's very similar to https://github.com/jruby/jruby/issues/2286 .. still not sure how to fix this.

**Comment by kares** [comment] 2015-04-10 13:34
@ebbflowgo that is something different (and fixed with latest 1.3.x) - just look at it closely on your own ...

**Comment by kares** [comment] 2015-04-24 06:24
as of now, seems as a JRuby compatibility issue however it's also been reported previously https://github.com/rails/rails/issues/16370

**Comment by kares** [comment] 2015-04-27 11:01
... confirmed this to be a JRuby 1.7.19 issue ... works fine with current 1.7.20-SNAPSHOT

**Closed by kares** 2015-04-27 11:01 UTC
Labels: invalid
