### ISSUE TITLE
Caused by: ArgumentError: Index name 'sqlite_autoindex_table_1' on table 'table' already exists

### ISSUE THREAD

**Issue by fbadigital** [jruby/activerecord-jdbc-adapter#895] opened 2018-05-07 19:12 UTC
Sqlite3 creates an auto_index if the primary key is different from the expected default (INTEGER PRIMARY KEY)
In this case you should ignore this type of index in method:
````
file: activerecord-jdbc-adapter-51.0/lib/arjdbc/sqlite3/adapter.rb
266:    # Returns an array of indexes for the given table.
267:     def indexes(table_name, name = nil) #:nodoc:
````
below is the patch so that this type of index is ignored:
````
273a274
>       indexes = []
274a276
>        unless row["name"].start_with?('sqlite_autoindex_')
287c289
<         IndexDefinition.new(
---
>         indexes << IndexDefinition.new(
293a296
>        end
294a298
>       return indexes
````
result:
````
...266...
    # Returns an array of indexes for the given table.
    def indexes(table_name, name = nil) #:nodoc:
      if name
        ActiveSupport::Deprecation.warn(<<-MSG.squish)
            Passing name to #indexes is deprecated without replacement.
          MSG
      end

      indexes = []
      exec_query("PRAGMA index_list(#{quote_table_name(table_name)})", "SCHEMA").map do |row|
       unless row["name"].start_with?('sqlite_autoindex_')
        sql = <<-SQL
            SELECT sql
            FROM sqlite_master
            WHERE name=#{quote(row['name'])} AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name=#{quote(row['name'])} AND type='index'
          SQL
        index_sql = exec_query(sql).first["sql"]
        match = /\sWHERE\s+(.+)$/i.match(index_sql)
        where = match[1] if match
        indexes << IndexDefinition.new(
          table_name,
          row["name"],
          row["unique"] != 0,
          exec_query("PRAGMA index_info('#{row['name']}')", "SCHEMA").map { |col|
            col["name"]
          }, nil, nil, where)
       end
      end
      return indexes
    end
...301...
````

**Comment by enebo** [comment] 2018-05-10 11:54
@fbadigital Can you verify whether 5.1.x of AR has this same issue with MRI?  We are using the same method definition and I can see in 5.2 they seem to have changed this method a bit.  I am not looking very closely but it does not look like it addresses tihs?  I am really curious about whether MRI has the same issue because it could be they strip out these rows in the native adapter?

We have lofty goal of match AR code exactly when it is reasonable so I am trying to gauge how neccesary diverging will be.

**Comment by fbadigital** [comment] 2018-05-10 20:38
I'm created a test ambient for simulate the situation:
````
#ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
#sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
#rails --versionls
Rails 5.1.0
#bundler  install
...
Using rake 12.3.1
Using activemodel 5.1.6
Using activerecord 5.1.6
Using bundler 1.16.1
Using ruby_dep 1.3.1
Using rails 5.1.6
Using sqlite3 1.3.13
...
Bundle complete! 14 Gemfile dependencies, 67 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

````

````
file: db/migrate/01_a.rb
class A < ActiveRecord::Migration[5.1]
  def self.up
    ActiveRecord::Base.logger = Logger.new(STDOUT)
   create_table :t, id: :string  do |t|
      t.string   :a,index: true
      t.string   :b
      t.string   :c
    end
  end
end
````
````
file: db/migrate/02_b.rb
class B < ActiveRecord::Migration[5.1]
  def change
    remove_column :t,  :b
  end
end
````
````
rake db:migrate
== 1 A: migrating =============================================================
-- create_table(:t, {:id=>:string})
D, [2018-05-10T20:23:08.673779 #5926] DEBUG -- :    (0.4ms)  SELECT sqlite_version(*)
D, [2018-05-10T20:23:08.675249 #5926] DEBUG -- :    (0.7ms)  CREATE TABLE "t" ("id" varchar NOT NULL PRIMARY KEY, "a" varchar, "b" varchar, "c" varchar)
D, [2018-05-10T20:23:08.679928 #5926] DEBUG -- :    (1.5ms)              SELECT sql
            FROM sqlite_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'

D, [2018-05-10T20:23:08.680436 #5926] DEBUG -- :    (0.2ms)  CREATE  INDEX "index_t_on_a" ON "t" ("a")
   -> 0.0221s
== 1 A: migrated (0.0235s) ====================================================

D, [2018-05-10T20:23:08.709946 #5926] DEBUG -- :   SQL (0.3ms)  INSERT INTO "schema_migrations" ("version") VALUES (?)  [["version", "1"]]
D, [2018-05-10T20:23:08.723483 #5926] DEBUG -- :    (12.3ms)  commit transaction
I, [2018-05-10T20:23:08.723982 #5926]  INFO -- : Migrating to B (2)
D, [2018-05-10T20:23:08.734377 #5926] DEBUG -- :    (0.1ms)  begin transaction
== 2 B: migrating =============================================================
-- remove_column(:t, :b)
D, [2018-05-10T20:23:08.757283 #5926] DEBUG -- :    (1.5ms)  CREATE TEMPORARY TABLE "at" ("id" varchar NOT NULL PRIMARY KEY, "a" varchar DEFAULT NULL, "b" varchar DEFAULT NULL, "c" varchar DEFAULT NULL)
D, [2018-05-10T20:23:08.759095 #5926] DEBUG -- :    (0.4ms)              SELECT sql
            FROM sqlite_master
            WHERE name='index_t_on_a' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='index_t_on_a' AND type='index'

D, [2018-05-10T20:23:08.761840 #5926] DEBUG -- :    (0.2ms)              SELECT sql
            FROM sqlite_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'

D, [2018-05-10T20:23:08.772618 #5926] DEBUG -- :    (0.2ms)  CREATE  INDEX "tindex_at_on_a" ON "at" ("a")
D, [2018-05-10T20:23:08.783926 #5926] DEBUG -- :    (3.2ms)  INSERT INTO "at" ("id","a","b","c")
                     SELECT "id","a","b","c" FROM "t"
D, [2018-05-10T20:23:08.784956 #5926] DEBUG -- :    (0.8ms)  DROP TABLE "t"
D, [2018-05-10T20:23:08.807285 #5926] DEBUG -- :    (0.3ms)  CREATE TABLE "t" ("id" varchar NOT NULL PRIMARY KEY, "a" varchar DEFAULT NULL, "c" varchar DEFAULT NULL)
D, [2018-05-10T20:23:08.817411 #5926] DEBUG -- :    (5.9ms)              SELECT sql
            FROM sqlite_master
            WHERE name='tindex_at_on_a' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='tindex_at_on_a' AND type='index'

D, [2018-05-10T20:23:08.817988 #5926] DEBUG -- :    (0.1ms)              SELECT sql
            FROM sqlite_master
            WHERE name='sqlite_autoindex_at_1' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='sqlite_autoindex_at_1' AND type='index'

D, [2018-05-10T20:23:08.820315 #5926] DEBUG -- :    (0.1ms)              SELECT sql
            FROM sqlite_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'

D, [2018-05-10T20:23:08.821174 #5926] DEBUG -- :    (0.5ms)  CREATE  INDEX "index_t_on_a" ON "t" ("a")
D, [2018-05-10T20:23:08.830386 #5926] DEBUG -- :    (2.5ms)  INSERT INTO "t" ("id","a","c")
                     SELECT "id","a","c" FROM "at"
D, [2018-05-10T20:23:08.831350 #5926] DEBUG -- :    (0.5ms)  DROP TABLE "at"
   -> 0.0965s
== 2 B: migrated (0.0966s) ====================================================

D, [2018-05-10T20:23:08.833022 #5926] DEBUG -- :   SQL (0.5ms)  INSERT INTO "schema_migrations" ("version") VALUES (?)  [["version", "2"]]
D, [2018-05-10T20:23:08.845991 #5926] DEBUG -- :    (12.1ms)  commit transaction
D, [2018-05-10T20:23:08.880586 #5926] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.9ms)  SELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? LIMIT ?  [["key", "environment"], ["LIMIT", 1]]
D, [2018-05-10T20:23:08.935366 #5926] DEBUG -- :    (3.7ms)  begin transaction
D, [2018-05-10T20:23:08.941112 #5926] DEBUG -- :    (0.1ms)  commit transaction
D, [2018-05-10T20:23:08.965993 #5926] DEBUG -- :    (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2018-05-10T20:23:08.979064 #5926] DEBUG -- :    (0.2ms)              SELECT sql
            FROM sqlite_master
            WHERE name='index_t_on_a' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='index_t_on_a' AND type='index'

D, [2018-05-10T20:23:08.979879 #5926] DEBUG -- :    (0.2ms)              SELECT sql
            FROM sqlite_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'
            UNION ALL
            SELECT sql
            FROM sqlite_temp_master
            WHERE name='sqlite_autoindex_t_1' AND type='index'
````
````
file: db/schema.rb 
...
ActiveRecord::Schema.define(version: 2) do

  create_table "t", id: :string, force: :cascade do |t|
    t.string "a"
    t.string "c"
    t.index ["a"], name: "index_t_on_a"
    t.index ["id"], name: "sqlite_autoindex_t_1", unique: true
  end

end
````

**Comment by enebo** [comment] 2018-05-15 19:34
I have confirmed that master runs this fine and 51.0 fails as described.  I am closing this since we fixed it in latest round of fixes.

**Closed by enebo** 2018-05-15 19:34 UTC
