### ISSUE TITLE
Creating a record with composite primary key 

### ISSUE THREAD

**Issue by mmustala** [jruby/activerecord-jdbc-adapter#756] opened 2016-10-17 16:40 UTC
Hi,

I have a table "results" whose primary key composes of three columns "job_id", "entry_at" and "type". I'm using PostgreSQL with Citus extension and this is a distributed table. It means that I have turned prepared statemenes and returning off by adding the following lines into the database.yml

```
prepared_statements: false
insert_returning: false
```

Now when I try to create a new record I get an error

```
jruby-9.1.2.0 :001 > r = Result::Graph.create!(job_id: 874, entry_at: Time.now)
ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: invalid name syntax
  Position: 16: SELECT currval('"results"_job_id,entry_at,type_seq')
    from arjdbc/jdbc/RubyJdbcConnection.java:888:in `execute_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-jdbc-adapter-1.3.21/lib/arjdbc/jdbc/adapter.rb:455:in `block in exec_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-jdbc-adapter-1.3.21/lib/arjdbc/jdbc/adapter.rb:455:in `exec_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-jdbc-adapter-1.3.21/lib/arjdbc/jdbc/adapter.rb:542:in `select'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-jdbc-adapter-1.3.21/lib/arjdbc/postgresql/adapter.rb:698:in `last_insert_id_result'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-jdbc-adapter-1.3.21/lib/arjdbc/postgresql/adapter.rb:597:in `exec_insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/relation.rb:64:in `insert'
```

When I tried the same using the master branch the error was pretty much the same.

```
jruby-9.1.2.0 :001 > r = Result::Graph.create!(job_id: 874, entry_at: Time.now)
ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: invalid name syntax
  Position: 16
    from arjdbc/jdbc/RubyJdbcConnection.java:1114:in `execute_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/bundler/gems/activerecord-jdbc-adapter-8c734333384b/lib/arjdbc/jdbc/adapter.rb:448:in `block in exec_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/bundler/gems/activerecord-jdbc-adapter-8c734333384b/lib/arjdbc/jdbc/adapter.rb:448:in `exec_query'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/bundler/gems/activerecord-jdbc-adapter-8c734333384b/lib/arjdbc/jdbc/adapter.rb:535:in `select'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/bundler/gems/activerecord-jdbc-adapter-8c734333384b/lib/arjdbc/postgresql/adapter.rb:681:in `last_insert_id_result'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/bundler/gems/activerecord-jdbc-adapter-8c734333384b/lib/arjdbc/postgresql/adapter.rb:580:in `exec_insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
    from /home/mika/.rvm/gems/jruby-9.1.2.0@c-java/gems/activerecord-4.2.5/lib/active_record/relation.rb:64:in `insert'
```

Is there some switch that I need to change or is this a case that is not currently handled and more code is needed for it?
##

**Comment by kares** [comment] 2017-05-06 11:31
expected to be a duplicate of #773

**Closed by kares** 2017-05-06 11:31 UTC
Labels: postgres, rails-4.2
