### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by kalaschnikow** [jruby/activerecord-jdbc-adapter#643] opened 2015-04-22 19:45 UTC
Hi,
in jirb
irb(main):001:0> require 'active_record'
=> true
irb(main):002:0>
irb(main):003:0* ActiveRecord::Base.establish_connection(
irb(main):004:1*     :adapter   => 'jdbcmysql',
irb(main):005:1*     :reconnect => true,
irb(main):006:1*     :database  => 'XXX',
irb(main):007:1*     :pool      => 5,
irb(main):008:1*     :username  => 'XXX',
irb(main):009:1*     :password  => 'XXX',
irb(main):010:1*     :host      => 'localhost'
irb(main):011:1> )

I get ==>
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern

in padrino everything is working...!!!!

what can I do?? any suggestions??
markus

**Comment by kares** [comment] 2015-04-24 06:20
able to reproduce and it's not just 4.2 that fails unexpectedly under JRuby : 
```
jruby-1.7.19 :001 > require 'active_record'
 => true 
jruby-1.7.19 :002 > ActiveRecord::Base.establish_connection( :adapter => 'oracle' )
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:587 warning: already initialized constant Reference
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:37 warning: already initialized constant MAPPING
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:189 warning: already initialized constant UTC_OFFSET_WITH_COLON
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/values/time_zone.rb:190 warning: already initialized constant UTC_OFFSET_WITHOUT_COLON
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:40 warning: already initialized constant BLACKLISTED_ARRAY_METHODS
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/concern.rb:126:in `included'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:54:in `ClassSpecificRelation'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:51:in `Delegation'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:6:in `ActiveRecord'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:5:in `(root)'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /opt/local/rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/base.rb:1:in `(root)'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.2.1/lib/active_record/base.rb:23:in `(root)'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from (irb):1:in `(root)'
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /opt/local/rvm/rubies/jruby-1.7.19/bin/irb:13:in `(root)'
```

```
jruby-1.7.19 :001 > gem 'activerecord', '4.0.13'
 => true 
jruby-1.7.19 :002 > require 'active_record'
 => true 
jruby-1.7.19 :003 > ActiveRecord::Base.establish_connection( :adapter => 'oracle' )
/opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:556 warning: already initialized constant Reference
NameError: Undefined method == for class 'ActiveSupport::ProxyObject'
	from org/jruby/RubyModule.java:2330:in `undef_method'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/proxy_object.rb:5:in `ProxyObject'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/proxy_object.rb:4:in `ActiveSupport'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/proxy_object.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /opt/local/rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:1:in `(root)'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /opt/local/rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/duration.rb:1:in `(root)'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:1:in `(root)'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
... 14 levels...
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/time.rb:12:in `(root)'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /opt/local/rvm/gems/jruby-1.7.19@jdbc/gems/activerecord-4.0.13/lib/active_record/base.rb:6:in `(root)'
	from (irb):1:in `(root)'
	from (irb):3:in `evaluate'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /opt/local/rvm/rubies/jruby-1.7.19/bin/irb:13:in `(root)'jruby-1.7.19 :004 > exit
```
please note that you're not loading any AR-JDBC code, closing as duplicate of #638
... this is likely related to load-path expansion which should be fixed in JRuby 1.7.20

**Closed by kares** 2015-04-24 06:20 UTC
